export const environment = {
  production: false,
  serverBaseUrl: 'http://localhost:3000',
  serverBaseUrlBackend: 'http://localhost:3000',
  usersEndpointPath: '/users',
  rolesEndpointPath: '/roles',
  profilesEndpointPath: '/profiles',
  subscriptionsEndpointPath: '/subscriptions',
  suppliersEndpointPath: '/users',
  recipesEndpointPath: 'http://localhost:8080/api/v1/recipes',
  suppliesEndpointPath: '/supplies',
  categoriesEndpointPath: '/supply_categories',
  unitMeasurementsEndpointPath: '/units_measurement',
  batchesEndpointPath: '/batches',
  restaurantSales: '/sales',
  salesRecipes: '/sales_recipes',
  ordersToSupplierEndpointPath: '/orders_to_supplier',
  ordersToSupplierStatesEndpointPath: '/orders_to_supplier_states',
  ordersToSupplierSituationsEndpointPath: '/orders_to_supplier_situations',
  ordersToSupplierBatchesEndpointPath: '/orders_to_supplier_batches',
  restaurantContactsEndpointPath: '/restaurant_contacts',
  orderCommentsEndpointPath: '/orders_comments',
  businessEndpointPath: '/businesses',
  customSuppliesEndpointPath: '/custom-supplies',
  catalogSuppliesEndpointPath: '/supplies'
};
